### ISSUE TITLE
Incorrect Mouser Part Number

### ISSUE THREAD

**Issue by mikerm19** [schlae/plaid-bib-cpld#1]
Mouser part numbers are duplicated on items 1 and 2 on PlaidBibCPLD.csv.

**Comment by mikerm19** [comment]
It looks like 594-K105K20X7RF5TH5 (1uf) might be a good one to get?

**Comment by schlae** [comment]
Yeah that looks good. 0.1uF ought to work OK too, but I'll update the BOM with your recommendation.

**Comment by mikerm19** [comment]
Ah ok, I wasn't sure. Thanks!
