### ISSUE TITLE
Works perfectly on my Model 70

### ISSUE THREAD

**Issue by figgy78** [schlae/plaid-bib-cpld#2]
Not an issue at all, but good news: The Plaid Bib CPLD works perfectly on my IBM PS/2 Model 70. You can add that to your list ;)

**Comment by vossi1** [comment]
Have you extra cards in your 70 that run in the system without problems?

II read that the card with cpld doesnt run with scsi-cards, but here i read it runs in the 9595 - and this is a scsi-only machine?

**Comment by figgy78** [comment]
@vossi1 
I have a RAM-card that works perfectly. Nothing else.
And no SCSI.

**Comment by vossi1** [comment]
@figgy78 Thanks for the info.
What Board Type / CPU-Type?
I think there are type 1,2,3 with 16,20,25 MHz

**Comment by vossi1** [comment]
any answer for me? 
...or for my other questions?
My card is not detected in my model 70. The system doesnt start - black screen only.  After pulling the card - it starts...

**Comment by figgy78** [comment]
Hi @vossi1 
Did you buy this card or solder it yourself? Did you burn the roms to CPLD?
If so, it could be a bad solder joint. 

All I have is a RAM-card and this card. Works perfectly. No SCSI. This is not a SCSI-only machine btw. 
Not sure about the CPU and FPU I have.  I think it's 16 Mhz?

**Comment by schlae** [comment]
Checking for bad solder joints is a good idea. When experimenting with the Snark Barker MCA (similar bus interface design) I had one that caused the machine to not boot at all (black screen) and it turns out there was a solder bridge between two pins on the CPLD. Inspect it very carefully under a microscope!
