### ISSUE TITLE
Does the cpld-version work with scsi-adapters?

### ISSUE THREAD

**Issue by vossi1** [schlae/plaid-bib-cpld#3]
II read in a forum that the card with cpld doesn't run with scsi-cards, but here i read it runs in the 9595 - and this is a scsi-only machine?

**Comment by schlae** [comment]
do you have a link to the forum post?

it works fine in my 9595 which uses SCSI.

**Comment by vossi1** [comment]
https://dosreloaded.de/forum/index.php?thread/2870-microchannel-adlib-plaid-bib-sound-mca/&postID=109708#post109708

Answer #24 in German

**Comment by schlae** [comment]
Ah, it would have been nice if that person had listed the precise model of the computer and the SCSI card.
